# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Music Player' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Music Player
  pod 'Firebase/Core'
  pod ‘FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'FirebaseUI/Google'
  pod 'Firebase/Firestore'
  target 'Music PlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Music PlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
